<? include "header.phtml"; ?>
  <h1><?=$this->escape($this->title);?></h1>
  <div id="description">
    <?=$this->escape($this->description);?>
  </div>
  <div id="error_message">
    <?=nl2br(htmlspecialchars($this->error_message));?>
  </div>
  <form name="website" method="post" action="<?=$this->escape($this->action)?>">
  <table>
    <tr>
	  <td><?=$this->escape($this->label_wname)?></td>
	  <td><input type="text" name="website_title" value="<?=$this->escape($this->website_title)?>"></td>
	</tr>
    <tr>
	  <td><?=$this->escape($this->label_wurl)?></td>
	  <td><input type="text" name="website_url" value="<?=$this->escape($this->website_url)?>"></td>
	</tr>	
  </table>
  <input type="submit" name="submit" value="<?=$this->escape($this->label_submit);?>">
  </form>
<? include "footer.phtml"; ?>
