<? include "header.phtml"; ?>
  <h1><?=$this->escape($this->title);?></h1>
		  <div id="error_message">
    <?=nl2br(htmlspecialchars($this->error_message));?>
  </div>

  <form method='post' action='<?=$this->escape($this->action);?>'>
  <table>
    <tr>
	  <td><?=$this->escape($this->username);?></td>
	  <td><input type='text' name='username'></td>
	</tr>
    <tr>
	  <td><?=$this->escape($this->password);?></td>
	  <td><input type='password' name='password'></td>
	</tr>	
  </table>
  <input type='submit' name='login' value='Login'>
  </form>
		<p>New User :<a href="register">Register Now</a><p>
<? include "footer.phtml"; ?>