   <table border="1" id="myTable">
    <tr>
	  <th>ID</th>
	  <th>User Name</th>	  
	  <th>First Name</th>	  
	  <th>Last Name</th>	  
	  <th>Status</th>	  
	  <th>Action</th>	  
	</tr>
  <? $datas = $this->datas;
     for($i = 0; $i< count($datas);$i++){ ?>
    <tr>
	  <td><?=$datas[$i]['id']?></td>	
	  <td><?=$datas[$i]['user_email_address']?></td>
	  <td><?=$datas[$i]['first_name']?></td>	  
	  <td><?=$datas[$i]['last_name']?></td>	  
	  <td><?=$datas[$i]['status']?></td>	  
	  <td><span id="status_<?=$datas[$i]['id']?>">
			<?if($datas[$i]['status']=='active'){?>
	    <a onclick="getContents('<?=$this->projectUrl?>admin/cinactive/id/<?=$datas[$i]['id']?>','status_<?=$datas[$i]['id']?>')">Inactivate</a>
			<?}else{?>
	    <a onclick="getContents('<?=$this->projectUrl?>admin/cactive/id/<?=$datas[$i]['id']?>','status_<?=$datas[$i]['id']?>')">Activate</a>
			<?}?></span>
		|
	    <a href="<?=$this->projectUrl?>user/edit/id/<?=$datas[$i]['id']?>">Edit</a>
		|
	    <a onclick="return deleteClient(this);" id="del_<?=$datas[$i]['id']?>">Delete</a>		
	  </td>	  
	</tr> 
  <? } ?>
  </table>
  <div  id="paginator" ><?=($this->display_page);?></div>
