<table border="1">
	<tr>
		<th>ID</th>
		<th>User Name</th>	  
		<th>First Name</th>	  
		<th>Last Name</th>	  
		<th>Status</th>	  
		<th>Action</th>	  
 </tr>
	<? $datas = $this->datas;
				for($i = 0; $i< count($datas);$i++){ ?>
			<tr>
		<td><?=$datas[$i]['id']?></td>	
		<td><?=$datas[$i]['user_email_address']?></td>
		<td><?=$datas[$i]['first_name']?></td>	  
		<td><?=$datas[$i]['last_name']?></td>	  
		<td><?=$datas[$i]['status']?></td>	  
		<td>
				<a href="<?=$this->base_url?>/edit/id/<?=$datas[$i]['id']?>">Edit</a>
	|
				<a href="<?=$this->base_url?>/del/id/<?=$datas[$i]['id']?>">Delete</a>		
		</td>	  
 </tr> 
	<? } ?>
</table>
<div  id="paginator" ><?=($this->display_page);?></div>
